config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("urlly.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("ultrarapidlinks/", include("urlly.ultrarapidlinks.urls", namespace="ultrarapidlinks")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

urlly/ultrarapidlinks/urls.py
from django.urls import path

from .views import URLCreateView, URLUpdateView, URLDetailView, URLRedirectView, URLListView, StoredURLAPI

app_name = "ultrarapidlinks"

urlpatterns = [
    path('api/<slug:slug>/', view=StoredURLAPI.as_view(), name="api"), # REST addition
    path("", view=URLCreateView.as_view(), name="create"),
    path("list/", view=URLListView.as_view(), name="list"),
    path("detail/<slug:slug>/", view=URLDetailView.as_view(), name="detail"),
    path("update/<slug:slug>/", view=URLUpdateView.as_view(), name="update"),
    path("<slug:slug>/", view=URLRedirectView.as_view(), name="redirect"),
]

urlly/users/urls.py
from django.urls import path

from urlly.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

urlly/ultrarapidlinks/models.py
from django.db import models
from django.utils.crypto import get_random_string
from django.urls import reverse
from django.conf import settings

from model_utils.models import TimeStampedModel

class StoredURL(TimeStampedModel):
    url = models.URLField("Real URL", unique=True)
    descriptor = models.CharField("URL Descriptor", blank=True, max_length=255)
    slug = models.SlugField("Internal slug", unique=True, blank=True)
    counter = models.IntegerField("Usage counter", default=0, blank=False)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        slug_save(self, 5)
        super(StoredURL, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("ultrarapidlinks:detail", kwargs={"slug": self.slug})

    def __str__(self):
        return str(self.url)

def slug_save(obj, length):
    if not obj.slug:
        obj.slug = get_random_string(length)
        slug_invalid = True
        while slug_invalid:
            slug_invalid = False
            same_type_objects = type(obj).objects.filter(slug=obj.slug)
            if len(same_type_objects) > 0:
                slug_invalid = True
            if slug_invalid:
               obj.slug = get_random_string(length)

urlly/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for URL.ly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

urlly/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

urlly/ultrarapidlinks/views.py
from django.views.generic import CreateView, DetailView, RedirectView, ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404

from rest_framework import permissions, authentication
from rest_framework.views import APIView
from rest_framework.response import Response

from .models import StoredURL
from .serializers import StoredURLSerializer

class URLCreateView(LoginRequiredMixin, CreateView):
    model = StoredURL
    fields = ['url', 'descriptor']

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)

class URLListView(LoginRequiredMixin, ListView):
    model = StoredURL
    queryset = StoredURL.objects.all()

    def get_queryset(self):
        return StoredURL.objects.filter(creator=self.request.user).order_by("created").reverse()

class URLDetailView(LoginRequiredMixin, DetailView):
    model = StoredURL
    fields = ['url', 'descriptor', 'slug']

class URLRedirectView(RedirectView):
    permanent = False
    query_string = True
    pattern_name = "redirect"

    def get_redirect_url(self, *args, **kwargs):
        url_object = get_object_or_404(StoredURL, slug=kwargs["slug"])
        url_object.counter += 1
        url_object.save() 
        return url_object.url

class URLUpdateView(LoginRequiredMixin, UpdateView):
    model = StoredURL
    fields = ['url', 'descriptor']
    action = "Update"

# REST addition.

class StoredURLAPI(APIView):
    authentication_classes = [authentication.TokenAuthentication]
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def get(self, request, *args, **kwargs):
        url = get_object_or_404(StoredURL, slug=kwargs["slug"])
        serializer = StoredURLSerializer(url, many=False)
        return Response(serializer.data)

urlly/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

urlly/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}URL.ly{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">URL.ly</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#", role="button" aria-haspopup="true" aria-expanded="false">Links</a>
              <div class="dropdown-menu"> 
                <a class="dropdown-item" href="{% url 'ultrarapidlinks:create' %}">Create new link</a>
                <a class="dropdown-item" href="{% url 'ultrarapidlinks:list' %}">View my links</a>
              </div>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

urlly/templates/pages/about.html
{% extends "base.html" %}

{% block content %}
    <h1>About us</h1>
    <p>Welcome to URL.ly, a simple bit.ly style service.</p>
    <p>This service was created <s>out of boredom</s> for Django practice somewhere around 2020</p>
{% endblock %}

urlly/templates/pages/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome!</h1>
{% endblock %}

urlly/templates/ultrarapidlinks/storedurl_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Url Detail
{% endblock %}

{% block  javascript %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/ultrarapidlinks.js' %}"></script>
{% endblock %}

{% block content %}
    {% with descriptor=object.descriptor|default:"Your URL" %}
        <h1>{{ descriptor }}</h1>
    {% endwith %}
    <div class="container">
        <div class="row">
            <div class="input-group">
                <div class="custom-file">
                    <input type="text" class="form-control" id="UrlInput" value={{ object.url }} readonly>
                </div>
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" onclick="ClipboardCopy()">&#128203</button>
                    <a class="btn btn-outline-secondary" href="{% url 'ultrarapidlinks:update' slug=storedurl.slug %}" role="button">&#9997</a>
                    <a class="btn btn-outline-secondary" href="{% url 'ultrarapidlinks:redirect' slug=storedurl.slug %}" role="button">&#10150</a>
                </div>
            </div>
        </div>
        <p>Number of visits: {{ object.counter }}</p>
    </div>
{% endblock  %}

urlly/templates/ultrarapidlinks/storedurl_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{view.action|default:"Create"}} short URL
{% endblock %}

{% block content %}
{% with action=view.action|default:"Add"  %}
    <h1>{{view.action|default:"Create"}} </h1>
    <form class="form-horizontal" method="post" action=".">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
    </form>
{% endwith %}
{% endblock %}

urlly/templates/ultrarapidlinks/storedurl_list.html
{% extends 'base.html' %}

{% block title %}
    Link List
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-">
                <div class="sticky-top">
                <a class="btn btn-outline-secondary" href="{% url 'ultrarapidlinks:create' %}" role="button">&#10133</a>
                </div>
            </div>
            <div class="col">
                <table class="table table-borderless">
                <thead>
                    <tr>
                        <th scope="col" class="text-center">#</th>
                        <th scope="col" class="text-center">Name</th>
                        <th scope="col" class="text-center">Visits</th>
                        <th scope="col" class="text-center"></th>
                    </tr>
                </thead>
                <tbody>
                {% for storedurl in storedurl_list %}
                    <tr>
                    <th scope="row" class="text-center">{{ forloop.counter }}</th>
                    {% with name=storedurl.descriptor|default:storedurl.url %}
                        <td>{{ name }}</td>
                        <td class="text-center">{{ storedurl.counter }}</td>
                        <td>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                <a class="btn btn-outline-secondary" href="{% url 'ultrarapidlinks:redirect' slug=storedurl.slug %}" role="button">&#10150</a>
                                </div>
                                <a class="btn btn-outline-secondary rounded-0" href="{% url 'ultrarapidlinks:detail' slug=storedurl.slug %}" role="button">&#128269</a>
                                <div class="input-group-append">
                                <a class="btn btn-outline-secondary" href="{% url 'ultrarapidlinks:update' slug=storedurl.slug %}" role="button">&#9997</a>
                                </div>
                            </div>
                        </td>
                    {% endwith %}
                    </tr>
                {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

urlly/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

urlly/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}